/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */
#include "ClusterMessagesProto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(FillNodeParamsProto, FillNodeParamsProto, AUTO)


PB_BIND(BlitNodeParamsProto, BlitNodeParamsProto, AUTO)


PB_BIND(SetNodePixelParamsProto, SetNodePixelParamsProto, AUTO)


PB_BIND(QueueNodePixelParamsProto, QueueNodePixelParamsProto, AUTO)


PB_BIND(DequeueNodePixelParamsProto, DequeueNodePixelParamsProto, AUTO)


PB_BIND(ClusterMessageProto, ClusterMessageProto, AUTO)




