/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SRC_CORE_PROTO_CLUSTERMESSAGESPROTO_PB_H_INCLUDED
#define PB_SRC_CORE_PROTO_CLUSTERMESSAGESPROTO_PB_H_INCLUDED
#include <pb.h>
#include "pb_encode.h"
#include "pb_decode.h"
#include "pb_common.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _CommandTypeProto {
    CommandTypeProto_FILL_NODE = 0,
    CommandTypeProto_BLIT_NODE = 1,
    CommandTypeProto_FILL_BUFFER = 2,
    CommandTypeProto_BLIT_BUFFER = 3,
    CommandTypeProto_SET_NODE_PIXEL = 4,
    CommandTypeProto_QUEUE_NODE_PIXEL = 5,
    CommandTypeProto_DEQUEUE_NODE_PIXEL = 6
} CommandTypeProto;

/* Struct definitions */
typedef struct _ClusterMessageProto {
    int32_t cluster_id;
    CommandTypeProto command_type;
    int32_t param_node_id;
    uint32_t param_color;
    uint32_t param_pad_color;
    int32_t param_pixel_index;
    pb_callback_t param_colors;
} ClusterMessageProto;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _CommandTypeProto_MIN CommandTypeProto_FILL_NODE
#define _CommandTypeProto_MAX CommandTypeProto_DEQUEUE_NODE_PIXEL
#define _CommandTypeProto_ARRAYSIZE ((CommandTypeProto)(CommandTypeProto_DEQUEUE_NODE_PIXEL+1))

#define ClusterMessageProto_command_type_ENUMTYPE CommandTypeProto


/* Initializer values for message structs */
#define ClusterMessageProto_init_default         {0, _CommandTypeProto_MIN, 0, 0, 0, 0, {{NULL}, NULL}}
#define ClusterMessageProto_init_zero            {0, _CommandTypeProto_MIN, 0, 0, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ClusterMessageProto_cluster_id_tag       1
#define ClusterMessageProto_command_type_tag     2
#define ClusterMessageProto_param_node_id_tag    3
#define ClusterMessageProto_param_color_tag      4
#define ClusterMessageProto_param_pad_color_tag  5
#define ClusterMessageProto_param_pixel_index_tag 6
#define ClusterMessageProto_param_colors_tag     7

/* Struct field encoding specification for nanopb */
#define ClusterMessageProto_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    cluster_id,        1) \
X(a, STATIC,   SINGULAR, UENUM,    command_type,      2) \
X(a, STATIC,   SINGULAR, INT32,    param_node_id,     3) \
X(a, STATIC,   SINGULAR, UINT32,   param_color,       4) \
X(a, STATIC,   SINGULAR, UINT32,   param_pad_color,   5) \
X(a, STATIC,   SINGULAR, INT32,    param_pixel_index,   6) \
X(a, CALLBACK, REPEATED, UINT32,   param_colors,      7)
#define ClusterMessageProto_CALLBACK pb_default_field_callback
#define ClusterMessageProto_DEFAULT NULL

extern const pb_msgdesc_t ClusterMessageProto_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ClusterMessageProto_fields &ClusterMessageProto_msg

/* Maximum encoded size of messages (where known) */
/* ClusterMessageProto_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
